# Generated by Django 5.0 on 2023-12-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("user_name", models.CharField(max_length=255, unique=True)),
                ("user_email", models.EmailField(max_length=255, unique=True)),
                (
                    "user_phone_no",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("user_password", models.CharField(max_length=255)),
                ("user_type", models.CharField(max_length=10)),
                ("user_created_datetime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "User",
            },
        ),
    ]
